//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hausarbeit_Worldbuilding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Location
    {
        public int LocationID1 { get; set; }
        public int LocationID2 { get; set; }
        public string Description { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
    }
}
