//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hausarbeit_Worldbuilding
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldbuildingDBEntities : DbContext
    {
        public WorldbuildingDBEntities()
            : base("name=WorldbuildingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Gruppe> Gruppe { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<World> World { get; set; }
    }
}
